name: flightbank
description: "FlightBank — A Flutter banking app for the Learning to Fly tutorial."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.0.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
